apiVersion: v1
kind: Service
metadata:
  name: yolov8-service
spec:
  type: NodePort
  selector:
    app: yolov8
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30001
